### ISSUE TITLE
腾讯云cos上传图片一直是image uploading

### ISSUE THREAD

**Issue by luwantaoChina** [Spades-S/vs-picgo#12]
腾讯云cos上传图片一直是image uploading,我之前配置使用都是正常的。
![图片](https://user-images.githubusercontent.com/26440503/54942409-fc9fc400-4f69-11e9-9ba9-e3ee793b8c87.png)

**Comment by Spades-S** [comment]
@luwantaoChina  我这边测试时没有问题的，有可能是当时网络状况不好，当前版本的vs-picgo的报错提示还不是很友好，后面会做改进。 如果还是出现类似问题的话，可以贴一下日志信息，vscode -> Help -> Toggle Developer Tools
![image](https://user-images.githubusercontent.com/18718461/54968421-9b054700-4fb5-11e9-94b6-55546c7532a7.png)

**Comment by luwantaoChina** [comment]
多谢，是更新之后配置文件有变化，我修改了一下就好了
