### ISSUE TITLE
插件不能正常工作。。。

### ISSUE THREAD

**Issue by rxliuli** [Spades-S/vs-picgo#3]
- 当吾辈想要从 Explorer 或者 InputBox 选择一张图片上传时会发生错误：
Cannot read property 'silent' of undefined
- 当吾辈从截切板上传时发生的错误
Running the contributed command:'picgo.uploadImageFromClipboard' failed.

不清楚发生了什么，但 PC 版本能够正常使用，有什么好的解决方案么？(｡+･`ω･´)

**Comment by Spades-S** [comment]
> * 当吾辈想要从 Explorer 或者 InputBox 选择一张图片上传时会发生错误：
>   Cannot read property 'silent' of undefined
> * 当吾辈从截切板上传时发生的错误
>   Running the contributed command:'picgo.uploadImageFromClipboard' failed.
> 
> 不清楚发生了什么，但 PC 版本能够正常使用，有什么好的解决方案么？(｡+･`ω･´)

PC版本？出现错误的是在啥版本上呢？

**Comment by Molunerfinn** [comment]
@rxliuli @Spades-S 我在前一段时间开发的时候发现了一种可能导致上传失败的原因：VSCode自带的配置文件的json里头行不能有注释：

![image](https://user-images.githubusercontent.com/12621342/47191447-0cdbc380-d37a-11e8-8ed2-c706ed7fd798.png)
![image](https://user-images.githubusercontent.com/12621342/47191463-24b34780-d37a-11e8-8f5e-a397707d307e.png)
需要把注释去掉。原因是PicGo-Core读取配置文件的`lowdb`貌似只支持纯的`json`。回头我会去`lowdb`的官方仓库查看解决办法。
@rxliuli 你可以排查一下这个原因。
@Spades-S 可能需要写到README里防止以后其他人出现这个问题。

**Comment by Spades-S** [comment]
@Molunerfinn 应该是这个问题，加上注释确实复现了这个错误。
@rxliuli  试试把vscode配置文件中的注释行去掉看看

**Comment by Spades-S** [comment]
@rxliuli settings.json注释导致的插件Bug修复了

**Comment by Molunerfinn** [comment]
@Spades-S 不还有点问题...

**Comment by rxliuli** [comment]
额，那吾辈还是安心先用着客户端快捷键上传吧。。。┐(‘～`；)┌

PiEgg <notifications@github.com> 于2018年10月19日周五 下午4:37写道：

**Comment by Spades-S** [comment]
#11
