### ISSUE TITLE
文档中七牛的配置参数，缺少有关路径前缀的 key -- path

### ISSUE THREAD

**Issue by fortress-fight** [Spades-S/vs-picgo#4]
感谢您提供的插件

在使用的过程中，需要配置七牛的上传路径前缀，文档中关于七牛的配置项中缺少该项的配置。通过查询 PICGO 的代码，发现该参数为：path。

文档中没有关于 options 的介绍，通过查询该项为网址后缀，希望能在文档中补上，便于使用；

```json
{
"qiniu": {
            "accessKey": "******",
            "secretKey": "******",
            "bucket": "******",
            "url": "******",
            "area": "储存区域",
            "path": "resource/image/",
            "options": ""
        }
}
```

测试可用，希望有所帮助

**Comment by Spades-S** [comment]
这两个参数是可选项，目前在插件的文档里省略了，更新时会在文档中将两个参数补全。
非常感谢

**Comment by Spades-S** [comment]
@fortress-fight 
这两个参数是可选项，目前在插件的文档里省略了，更新时会在文档中将两个参数补全。
非常感谢
