### ISSUE TITLE
vs code 最新版中好像上传不了，不知道是不是我配置问题，还是大家也这样

### ISSUE THREAD

**Issue by xinde** [Spades-S/vs-picgo#5]
vs code 最新版中settings.json加入了完整配置，但是好像上传不了，进度条到最后就停了
默认的smms可以上传
```
 "picgo": {
    "path": ""
  },
  "picBed": {
    "current": "qiniu",
    "qiniu": {
...//相应的配置填入客户端可以上传成功
    }
  }
```
运行插件后，好像还会在setting里默认加上plugins属性

**Comment by Spades-S** [comment]
@xinde 
1. 七牛云配置
在配置七牛云的时候 要注意下 area 属性，其他的应该正常配置就可以了。方便贴一下你的配置么，目前我没有域名，没法测试😅
![image](https://user-images.githubusercontent.com/18718461/50511471-c23c9d00-0ac8-11e9-8561-b9684f8621e2.png)
2. usersetting.json 里多出来的 plugins 属性 是PicGo-Core 留出来给PicGo-Core的插件用的，这样直接放在usersetting.json里确实有点不大好， @Molunerfinn 蛋哥这里你看要不要调整一下?

**Comment by Molunerfinn** [comment]
plugins是预留给PicGo-Core的插件的。因为其实以后PicGo的一些插件可能也能直接运行在VSCode里，所以目前没有删掉的计划。也不会影响VSCode其他使用。

**Comment by Spades-S** [comment]
@Molunerfinn 我是觉得这个plugins属性 在usersetting.json 里指向不是很清晰，是不是可以考虑把属性名改成 picgoPlugin，或者在所有PicGo-Core属性外面包一层picgo属性， picgo:{picBed:{}, plugins:{}}， 这样相对会清晰一些

**Comment by xinde** [comment]
@Spades-S 谢谢，真的是区域问题，我写的是 ‘华东’。多谢！！！

**Comment by Molunerfinn** [comment]
@Spades-S 新版本发了，可以更新一下。
