### ISSUE TITLE
[Bug]: 选中文字再上传时出现错误

### ISSUE THREAD

**Issue by upupming** [Spades-S/vs-picgo#7]
## Steps to reproduce

1. Select some text:
    ![image](https://user-images.githubusercontent.com/24741764/51118670-e7ad0300-184b-11e9-888f-b47caa27d0b2.png)

2. Copy a picture to clipboard & hit `Ctrl + Alt + U`:

    ![upload-with-text-selected](https://user-images.githubusercontent.com/24741764/51118861-54280200-184c-11e9-93c0-055b8fbd06ae.gif)

## Expect behavior

I prefer to making the selection text as the Alt Text, for example:

select `demo-picture` and upload the picture will get result:

```
![demo-picture](...)
```

**Comment by upupming** [comment]
A log of `notice` from here 
https://github.com/Spades-S/vs-picgo/blob/72b66537a3f1f14b3bda380b211ade1dd6b97bed/src/extension.ts#L133-L136
will get:

![image](https://user-images.githubusercontent.com/24741764/51119177-1e374d80-184d-11e9-9879-f6a80fc538b7.png)

**Comment by upupming** [comment]
It seems to be a problem with PicGo itself, doesn't it? @Molunerfinn

**Comment by Molunerfinn** [comment]
SM.MS的上传有的时候会出现网络问题。
![image](https://user-images.githubusercontent.com/12621342/51123472-24322c00-1857-11e9-8ea3-fe606e0f0fc8.png)

**Comment by upupming** [comment]
1. 测试了一下，不选中文字上传是可以的，选中之后就会报错。
2. 果然，选中没有换行符的文字就可以：

![upload-with-text-selected-no-newline](https://user-images.githubusercontent.com/24741764/51126536-6317b000-185e-11e9-844b-6300fb09293a.gif)

至于选中带换行的文字上传会得到网络错误就不太清楚了 😅

**Comment by Molunerfinn** [comment]
@upupming 主要是因为在命令行和在PicGo软件里上传的时候文件名一般是正常的。所以上传后判断是否成功主要是靠`body.code`来判断，而一般网络问题导致失败的话回传的都是`false`。你这个情况应该是在vs-picgo端做一层正则替换，如果遇到`$`就忽略

**Comment by upupming** [comment]
嗯，谢谢！

**Comment by Molunerfinn** [comment]
@upupming 觉得好用也给这个库点个star哇~毕竟是第一个非官方的PicGo插件，速度超快

**Comment by Spades-S** [comment]
@upupming 在命名上我人为做了限制，遇到$符会认为不合法。
![image](https://user-images.githubusercontent.com/18718461/51164700-c5ad9200-18d8-11e9-99af-11b600e5cfcb.png)
@Molunerfinn 蛋哥说的过滤的效果会更好，我更新一下。
