### ISSUE TITLE
usersetting.json目录没有找到

### ISSUE THREAD

**Issue by cooper1x** [Spades-S/vs-picgo#9]
我用的是Windows 10，用everything都没有搜到……

**Comment by Spades-S** [comment]
打开设置，点击{}，setting.json就是用户设置文件
![image](https://user-images.githubusercontent.com/18718461/52610527-7600bd00-2ebc-11e9-8fdc-88e11fc0cc95.png)

**Comment by cooper1x** [comment]
为什么`"current": "tcyun"`设置了还是默认传到的sm呢？

**Comment by Molunerfinn** [comment]
@cooper1x 你的`current`设置要写在`picBed`里：
![image](https://user-images.githubusercontent.com/12621342/53147296-1acc7a00-35e2-11e9-8ef4-89187119392b.png)
我这边改了之后上传是没问题的

**Comment by cooper1x** [comment]
![image](https://user-images.githubusercontent.com/9080789/53216417-6c7f0e00-368f-11e9-951c-032e5b62934f.png)
我这样设置不对吗？

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/53217253-53c42780-3692-11e9-8c2c-bd0fea519b61.png)
请把这个path改成`''`,否则vs-picgo会去找这个path对应的配置文件。

**Comment by cooper1x** [comment]
好了，谢谢！

**Comment by yehbww** [comment]
@Molunerfinn 您好，我照上面的修改过了，但是图片还是上传到SMMS中。能帮着看一下吗？谢谢
![](https://raw.githubusercontent.com/yehbww/imagehosting/master/20190303223028.png)

**Comment by cooper1x** [comment]
@yehbww 你的也是picgo这个里面的path的value没有写成空字符串，你把path这个键删掉了是什么情况？

**Comment by yehbww** [comment]
我看说明里写的是默认值DEFAULT VALUE是""的话代表使用下方的picbed设置，所以我就留空了。

**Comment by cooper1x** [comment]
@yehbww 留空的是json的v，不是k……你理解错了

**Comment by yehbww** [comment]
我不是专业搞这个的，就是想用来传图处理文本的。对上面的语法不是太清楚。能直接给个示例吗？谢谢

**Comment by cooper1x** [comment]
@yehbww 
这里这样写
```
"picgo": {
    "path": ""
  },
```

**Comment by yehbww** [comment]
@Molunerfinn @cooper1x 谢谢。不过改过后还是传的是SMMS。请看以下这样改对吧？
![](https://raw.githubusercontent.com/yehbww/imagehosting/master/20190303224826.png)

**Comment by Molunerfinn** [comment]
@yehbww 不对...正确应该是：
```json
{
  "files.autoSave": "afterDelay",
  // ...其他配置项
  "picgo" : {
     path: ""
  },
  "picBed": {
    // 相应配置 
  }
}
```
配置项要写到一个`{}`内部

**Comment by cooper1x** [comment]
@Spades-S 默认的不是github啊，默认是的sm.ms。你有自己的图床吗？有的话需要写别的，没有的话只能用公共的了。
配置在这里可以看：
[Spades-S/vs-picgo: A vscode plugin for PicGo](https://github.com/Spades-S/vs-picgo)

**Comment by yehbww** [comment]
@cooper1x @Molunerfinn 我在GITHUB上建了一个图床，刚才提问附的图片就是用PICGO直接上传的。只是想在VSCODE中也利用起来。没想到改来改去还是没改对。谢谢，我再研究一下吧。谢谢大家了。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/53697002-74fde400-3e07-11e9-8508-b7a8e086988a.png)
你注意看你配置项有没有报错，你看这个红色波浪号就是提示你错误的

**Comment by Molunerfinn** [comment]
@Spades-S 可能需要优化一下配置项设置步骤。给个DEMO的GIF或者截图文档也好

**Comment by Molunerfinn** [comment]
```json
{
  "editor.fontSize": 18, //test
  "editor.fontFamily": "Roboto Mono Medium, \"Microsoft Yahei Mono\"",
  "editor.tabSize": 2,
  "editor.cursorStyle": "line",
  "picBed": {
    "current": "qiniu",
    "weibo": {
      "chooseCookie": true,
      "username": "",
      "password": "",
      "quality": "large",
      "cookie": ""
    },
    "qiniu": {
      "accessKey": "xxx",
      "secretKey": "xxx",
      "bucket": "xxx",
      "url": "xxx",
      "area": "z0",
      "options": "?imgslim",
      "path": ""
    }
  },
  "plugins": {},
  "editor.quickSuggestions": {
    "strings": true
  }
}
```
@yehbww 我自己的配置项DEMO，供参考。

**Comment by yehbww** [comment]
@Molunerfinn 好的，谢谢。确实在下面一段的“{”上有个红色报错，下面的解释是END OF FILE EXPECTED，其他倒没有报错。回头我照您的示例再修正一下吧。谢谢大家。

**Comment by Spades-S** [comment]
好  我找个时间更新一下文档

PiEgg <notifications@github.com>于2019年3月3日 周日下午10:56写道：

**Comment by Spades-S** [comment]
@yehbww usersetting.json的最外层只能有一个花括号块，所有的配置信息都要写在这个花括号块内，把配置文件里的picgo，picBed都移到第一个花括号内

**Comment by yehbww** [comment]
昨晚最后用的配置应该是符合您说的要求的，也没有任何报错了，branch里填的master，但还是不行，上传后的图床始终是LOLI。今天我再换台电脑试试。谢谢
![](https://raw.githubusercontent.com/yehbww/imagehosting/master/20190304100517.png)

**Comment by Spades-S** [comment]
@yehbww  我这里测试是可以上传的， 需要注意的是 repo的值是 用户名/仓库名，比如 test/Image-Hosting ，还有就是目前picgo-core中用的github api，是无法做到上传同名文件的，上传同名文件会报错

**Comment by yehbww** [comment]
@Spades-S 刚才我换了台电脑，试了一下，也成功了，可能还是哪个地方的语法有问题。刚才写的语法还是报错，就始终不能成功，连往SMMS上传都是失败的。改好后，一下子就能传到GITHUB上了。昨晚的REPO名称格式是正确的，和PICGO软件里的设置一样，PICGO里上传一直是成功的。回头再到原来那台电脑上试试。谢谢大家了。
